In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [5]:
data=pd.read_csv('Churn_Modelling.csv')
data.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
## Preprocessing the data
## Dropping the columns which are not required for training the model
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [7]:
data.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
## Encode Categorical varible 
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [9]:
data.head(15)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0
10,528,France,1,31,6,102016.72,2,0,0,80181.12,0
11,497,Spain,1,24,3,0.00,2,1,0,76390.01,0
12,476,France,0,34,10,0.00,2,1,0,26260.98,0
13,549,France,0,25,5,0.00,2,0,0,190857.79,0
14,635,Spain,0,35,7,0.00,2,1,1,65951.65,0

In [10]:
## One hot encoding for the categorical variable 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder() 
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [11]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df.head(5)

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [13]:
## Combine all onehotencoding column

data = pd.concat([data.drop('Geography',axis=1), geo_encoder_df], axis=1)
data.head(15)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0
10,528,1,31,6,102016.72,2,0,0,80181.12,0,1.0,0.0,0.0
11,497,1,24,3,0.00,2,1,0,76390.01,0,0.0,0.0,1.0
12,476,0,34,10,0.00,2,1,0,26260.98,0,1.0,0.0,0.0
13,549,0,25,5,0.00,2,0,0,190857.79,0,1.0,0.0,0.0
14,635,0,35,7,0.00,2,1,1,65951.65,0,0.0,0.0,1.0

In [14]:
data.head(5)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [15]:
import pickle

with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo, f)

In [16]:
## Divide the dataset into independent and dependent variable
X = data.drop('Exited', axis=1)
y = data['Exited']

## Split the dataset into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Scale these features
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [17]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8000, 12), (2000, 12), (8000,), (2000,))

In [18]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scalar, f)

In [19]:
X_train.shape

(8000, 12)

## ANN Implemeentation

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense   
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [ ]:
## Build Our ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), ## Hidden layer 1 connected with input layer(64 hidden neurons)
    Dense(32, activation='relu'), ## Hidden layer 2 (32 hidden neurons)
    Dense(1, activation='sigmoid') ## Output layer (1 output neuron for binary classification because we are using the sigmoid activation function)
])

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy(from_logits=False)
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [26]:
# Compile the model with Adam optimizer and binary cross-entropy loss function for binary classification
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
## Set up the TensorBoard callback to log training metrics for visualization in TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [29]:
## Set up early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [30]:
## Training the model 
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, callbacks=[early_stopping, tensorboard_callback])

Epoch 1/100
200/200 [==============================] - 1s 1ms/step - loss: 0.4589 - accuracy: 0.8027 - val_loss: 0.4054 - val_accuracy: 0.8331
Epoch 2/100
200/200 [==============================] - 0s 849us/step - loss: 0.4001 - accuracy: 0.8355 - val_loss: 0.3723 - val_accuracy: 0.8444
Epoch 3/100
200/200 [==============================] - 0s 828us/step - loss: 0.3653 - accuracy: 0.8511 - val_loss: 0.3536 - val_accuracy: 0.8525
Epoch 4/100
200/200 [==============================] - 0s 826us/step - loss: 0.3483 - accuracy: 0.8594 - val_loss: 0.3495 - val_accuracy: 0.8556
Epoch 5/100
200/200 [==============================] - 0s 824us/step - loss: 0.3417 - accuracy: 0.8602 - val_loss: 0.3454 - val_accuracy: 0.8469
Epoch 6/100
200/200 [==============================] - 0s 822us/step - loss: 0.3385 - accuracy: 0.8620 - val_loss: 0.3464 - val_accuracy: 0.8550
Epoch 7/100
200/200 [==============================] - 0s 833us/step - loss: 0.3348 - accuracy: 0.8602 - val_loss: 0.3430 - val_accuracy: 0.8544
Epoch 8/100
200/200 [==============================] - 0s 820us/step - loss: 0.3321 - accuracy: 0.8653 - val_loss: 0.3409 - val_accuracy: 0.8462
Epoch 9/100
200/200 [==============================] - 0s 809us/step - loss: 0.3301 - accuracy: 0.8642 - val_loss: 0.3421 - val_accuracy: 0.8506
Epoch 10/100
200/200 [==============================] - 0s 840us/step - loss: 0.3273 - accuracy: 0.8666 - val_loss: 0.3458 - val_accuracy: 0.8537
Epoch 11/100
200/200 [==============================] - 0s 846us/step - loss: 0.3255 - accuracy: 0.8656 - val_loss: 0.3387 - val_accuracy: 0.8519
Epoch 12/100
200/200 [==============================] - 0s 907us/step - loss: 0.3236 - accuracy: 0.8675 - val_loss: 0.3402 - val_accuracy: 0.8581
Epoch 13/100
200/200 [==============================] - 0s 863us/step - loss: 0.3221 - accuracy: 0.8684 - val_loss: 0.3365 - val_accuracy: 0.8512
Epoch 14/100
200/200 [==============================] - 0s 842us/step - loss: 0.3200 - accuracy: 0.8662 - val_loss: 0.3421 - val_accuracy: 0.8550
Epoch 15/100
200/200 [==============================] - 0s 906us/step - loss: 0.3184 - accuracy: 0.8692 - val_loss: 0.3377 - val_accuracy: 0.8512
Epoch 16/100
200/200 [==============================] - 0s 891us/step - loss: 0.3158 - accuracy: 0.8698 - val_loss: 0.3383 - val_accuracy: 0.8556
Epoch 17/100
200/200 [==============================] - 0s 869us/step - loss: 0.3159 - accuracy: 0.8681 - val_loss: 0.3444 - val_accuracy: 0.8531
Epoch 18/100
200/200 [==============================] - 0s 831us/step - loss: 0.3137 - accuracy: 0.8700 - val_loss: 0.3410 - val_accuracy: 0.8525

In [31]:
model.save('churn_model.h5')

/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [1]:
## load TensorBoard Extension
%load_ext autoreload

In [2]:
%load_ext tensorboard

In [3]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/bin/tensorboard", line 3, in <module>
    from tensorboard.main import run_main
  File "/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/lib/python3.11/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/lib/python3.11/site-packages/tensorboard/default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [5]:
import sys
print(sys.executable)

/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/bin/python

In [6]:
import tensorflow as tf
print(tf.__version__)
print(tf.__file__)

2.15.0
/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/lib/python3.11/site-packages/tensorflow/__init__.py

In [41]:
pip show tensorboard

Name: tensorboard
Version: 2.15.2
Summary: TensorBoard lets you watch Tensors Flow
Home-page: https://github.com/tensorflow/tensorboard
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/lib/python3.11/site-packages
Requires: absl-py, google-auth, google-auth-oauthlib, grpcio, markdown, numpy, protobuf, requests, setuptools, six, tensorboard-data-server, werkzeug
Required-by: tensorflow-macos
Note: you may need to restart the kernel to use updated packages.