In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle
import numpy as np  
from tensorflow.keras.models import load_model

In [5]:
import os

## Load the ANN trained model,onehot encoding model,scaler pickle files and the test data pickle file

model_path = 'churn_model.h5'
if not os.path.isfile(model_path):
    raise FileNotFoundError(f"{model_path} not found. Put the trained model file in the notebook folder or update the path.")
model = load_model(model_path)

## load the encoder and scaler 
with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder_gender = pickle.load(f)

with open('onehot_encoder_geo.pkl', 'rb') as f:
    onehot_encoder_geo = pickle.load(f)

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [6]:
## Example input data for prediction
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000.0,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000.0
}

In [7]:
## One hot encode the 'Geography' column
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

/Users/ranjitpawar/Documents/Deap_learning_project_with_ANN/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [8]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [9]:
## combine the input data with the encoded geography data
input_data = pd.concat([pd.DataFrame([input_data]), geo_encoded_df], axis=1)
input_data.drop('Geography', axis=1, inplace=True)

In [10]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000.0,2,1,1,50000.0,1.0,0.0,0.0

In [ ]:
input_df = pd.DataFrame(input_data)
input_df
input_df

ValueError: Must pass 2-d input. shape=(1, 1, 12)

In [ ]:
## Standard scalar for gender column
input_data['Gender'] = label_encoder_gender.transform(input_data['Gender'])